version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
    volumes:
      - ${PWD}/mongo_data:/data/db
    networks:
      - jc_network

  postgresdb:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: gs_db
    volumes:
      - ${PWD}/postgres_data:/var/lib/postgresql/data
    networks:
      - jc_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ${PWD}/rabbitmq_data:/var/lib/rabbitmq
    networks:
      - jc_network

  goweb:
    image: harrisonll/jc_gs:v1.2.0-linux
    container_name: goweb
    restart: always
    command: "./main --service=web" 
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgresdb
      - mongodb
      - rabbitmq
    volumes:
      - ${PWD}/worker_error_logs:/app/worker_error_logs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jc_network

  gocron:
    image: harrisonll/jc_gs:v1.2.0-linux
    container_name: gocron
    restart: always
    command: "./main --service=scheduler"
    env_file:
      - .env
    depends_on:
      - postgresdb
      - mongodb
      - rabbitmq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jc_network

  goemail:
    image: harrisonll/jc_gs:v1.2.0-linux
    container_name: goemail
    restart: always
    command: "./main --service=emailConsumer"
    env_file:
      - .env
    depends_on:
      - postgresdb
      - mongodb
      - rabbitmq
    networks:
      - jc_network

networks:
  jc_network:
    name: jc_network
    driver: bridge
